# This is a basic workflow to help you get started with Actions

name: http-monitor

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  schedule:
    - cron: '*/30 * * * *'
  push:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "watch-sfu"
  watch-sfu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: check sfu
      env:
        URL: $${{ secrets.SFU_URL }}
      run: curl URL
    - name: Slack Notification
      if: failure()
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_COLOR: '#c02020'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: 'SFU maybe down. Plase check it.'

  # This workflow contains a single job called "watch-talkin"
  watch-talkin:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: check web
      env:
        URL: $${{ secrets.WEB_URL }}
      run: curl URL
    - name: Slack Notification
      if: failure()
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_COLOR: '#c02020'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: 'Web maybe down. Plase check it.'

  # This workflow contains a single job called "watch-turn"
  watch-turn:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: check turn
      env:
        URL: $${{ secrets.TURN_URL }}
      run: curl URL
    - name: Slack Notification
      if: failure()
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_COLOR: '#c02020'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: 'TURN maybe down. Plase check it.'

